apiVersion: 1

datasources:
  - name: PostgreSQL-Joomla
    uid: postgresql-joomla
    type: postgres
    access: proxy
    url: database:5432
    user: joomla_user
    secureJsonData:
      password: joomla_pass123
    jsonData:
      database: joomladb       # <--- DEBE ESTAR AQUÍ DENTRO DE JSONDATA
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
